/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai10;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.*;

/**
 *
 * @author Than
 */
public class BangHienThi extends javax.swing.JFrame {
    private ArrayList<GiaoTiep> phong;
    private ArrayList<GiaoTiep> thietBi;
    private ArrayList<GiaoTiep> list;
    IOFile ioFile;
    /**
     * Creates new form BangHienThi
     */
    public BangHienThi() {
        initComponents();
        ioFile = new IOFile();
        phong = new ArrayList<>();
        thietBi = new ArrayList<>();
        list = new ArrayList<>();
        list = (ArrayList<GiaoTiep>) ioFile.docFile("QLTB.DAT");
        phong = (ArrayList<GiaoTiep>) ioFile.docFile("DSPHONG.DAT");
        thietBi= (ArrayList<GiaoTiep>) ioFile.docFile("DSTB.DAT");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDSPhong = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tenPhong = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        loadFile = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        soG = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableThietBi = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tenTB = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        namSX = new javax.swing.JComboBox<>();
        xx = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pID = new javax.swing.JTextField();
        tbID = new javax.swing.JTextField();
        load3Button = new javax.swing.JButton();
        add3Button = new javax.swing.JButton();
        clear3Button = new javax.swing.JButton();
        cancel3Button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sl = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tt = new javax.swing.JComboBox<>();
        edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        tk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        sapXep = new javax.swing.JComboBox<>();
        tttk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bảng Demo\n");

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 204));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setForeground(new java.awt.Color(153, 0, 153));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        tableDSPhong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tableDSPhong.setForeground(new java.awt.Color(0, 0, 204));
        tableDSPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "Số ghế"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableDSPhong.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tableDSPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDSPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDSPhong);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Tên Phòng");
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Số Ghế");

        tenPhong.setPreferredSize(new java.awt.Dimension(80, 30));
        tenPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenPhongActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addButton.setForeground(new java.awt.Color(0, 204, 0));
        addButton.setText("Add");
        addButton.setToolTipText("Click để thêm thông tin vào bảng");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(0, 204, 0));
        cancelButton.setText("Clear");
        cancelButton.setToolTipText("Click để xóa toàn bộ nội dung hiển thị khỏi bảng.");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        loadFile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loadFile.setForeground(new java.awt.Color(0, 204, 0));
        loadFile.setText("Load File");
        loadFile.setToolTipText("Chọn nút này để nạp thông tin từ file vào bảng");
        loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel.setForeground(new java.awt.Color(0, 204, 0));
        cancel.setText("Cancel");
        cancel.setToolTipText("Click để hủy thao tác vừa chọn");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("***Trường có nhãn màu ĐỎ không thể để trống");

        soG.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        soG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "150", "120", "100", "70", "60", "50" }));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 0));
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(soG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadFile)
                .addGap(34, 34, 34)
                .addComponent(addButton)
                .addGap(36, 36, 36)
                .addComponent(cancelButton)
                .addGap(34, 34, 34)
                .addComponent(cancel)
                .addGap(162, 162, 162))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(cancelButton)
                    .addComponent(loadFile)
                    .addComponent(cancel))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh Sách Phòng Học", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setMnemonic(KeyEvent.VK_A);
        jButton1.setText("Add");
        jButton1.setToolTipText("Click để thêm thông tin vừa nhập vào bảng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 0));
        jButton2.setMnemonic(KeyEvent.VK_L);
        jButton2.setText("Load File");
        jButton2.setToolTipText("Click nút này để nạp thông tin vào bảng từ file");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tableThietBi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tableThietBi.setForeground(new java.awt.Color(0, 0, 204));
        tableThietBi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã TB", "Tên TB", "Xuất Xứ", "Năm SX"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableThietBi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableThietBiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableThietBi);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 0));
        jButton3.setMnemonic(KeyEvent.VK_C);
        jButton3.setText("Clear");
        jButton3.setToolTipText("Click để xóa nội dung đang hiển thị khỏi bảng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 0));
        jButton4.setMnemonic(KeyEvent.VK_Z);
        jButton4.setText("Cancel");
        jButton4.setToolTipText("Click để hủy thao tác vừa chọn");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Tên TB");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Xuất Xứ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Năm SX");

        tenTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenTBActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("***Trường có nhãn màu đỏ không được để trống.");

        namSX.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        namSX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));

        xx.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        xx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Việt Nam", "Trung Quốc", "Nhật Bản", "Hàn Quốc", "Lào", "Thái Lan", "Hoa Kì", "Anh", "Đức", "Pháp", "Canada", "Đài Loan", "Nga" }));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 204, 0));
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(xx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(47, 47, 47)
                                    .addComponent(jButton3)
                                    .addGap(48, 48, 48)
                                    .addComponent(jButton4)))
                            .addComponent(tenTB, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tenTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(xx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(namSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh Sách Thiết Bị", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        table3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        table3.setForeground(new java.awt.Color(0, 0, 204));
        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "mã TB", "Tên TB", "Số Lượng", "Trạng Thái"
            }
        ));
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table3);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Mã Phòng");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Mã TB");

        tbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbIDActionPerformed(evt);
            }
        });

        load3Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        load3Button.setForeground(new java.awt.Color(0, 204, 0));
        load3Button.setMnemonic(KeyEvent.VK_L);
        load3Button.setText("Load File");
        load3Button.setToolTipText("Click để Tải thông tin từ file vào bảng hiển thị");
        load3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load3ButtonActionPerformed(evt);
            }
        });

        add3Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add3Button.setForeground(new java.awt.Color(0, 204, 0));
        add3Button.setMnemonic(KeyEvent.VK_A);
        add3Button.setText("Add");
        add3Button.setToolTipText("Click Add để thêm thông tin vào bảng");
        add3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add3ButtonActionPerformed(evt);
            }
        });

        clear3Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear3Button.setForeground(new java.awt.Color(0, 204, 0));
        clear3Button.setMnemonic(KeyEvent.VK_C);
        clear3Button.setText("Clear");
        clear3Button.setToolTipText("Click Cancel để xóa toàn bộ nội dung đang hiển thị trong bảng.");
        clear3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear3ButtonActionPerformed(evt);
            }
        });

        cancel3Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel3Button.setForeground(new java.awt.Color(0, 204, 0));
        cancel3Button.setMnemonic(KeyEvent.VK_Z);
        cancel3Button.setText("Cancel");
        cancel3Button.setToolTipText("Click để hủy bỏ thao tác.");
        cancel3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel3ButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Số Lượng");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 0));
        jLabel10.setText("Trạng Thái");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("***Các trường có nhãn màu đỏ không được bỏ trống.");

        tt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoạt động tốt", "Hỏng", "Khác" }));

        edit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        edit.setForeground(new java.awt.Color(0, 204, 0));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        save.setForeground(new java.awt.Color(0, 204, 0));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sl)
                    .addComponent(pID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(load3Button)
                                .addGap(32, 32, 32)
                                .addComponent(add3Button))
                            .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clear3Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancel3Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(136, 136, 136))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit)
                            .addComponent(save))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancel3Button)
                        .addComponent(clear3Button)
                        .addComponent(load3Button))
                    .addComponent(add3Button))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản Lí TB", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        table4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        table4.setForeground(new java.awt.Color(0, 0, 204));
        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "mã TB", "Tên TB", "Số Lượng", "Trạng Thái"
            }
        ));
        jScrollPane4.setViewportView(table4);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 204, 0));
        jButton7.setMnemonic(KeyEvent.VK_T);
        jButton7.setText("Tìm kiếm");
        jButton7.setToolTipText("Tìm kiếm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        tk.setText("Ví dụ 302-A2");
        tk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tkMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tkMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Nhập Tên phòng cần tìm kiếm:");

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 0, 204));
        jButton8.setMnemonic(KeyEvent.VK_L);
        jButton8.setText("Làm mới bảng");
        jButton8.setToolTipText("Làm mới nội dung để tìm kiếm nội dung mới");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 0, 0));
        jButton9.setMnemonic(KeyEvent.VK_C);
        jButton9.setText("Cancel");
        jButton9.setToolTipText("Hủy thao tác vừa thực hiện");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 204, 0));
        jButton10.setMnemonic(KeyEvent.VK_H);
        jButton10.setText("Hiển Thị");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("***Trường có nhãn màu đỏ không được để trống.");

        sapXep.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sắp Xếp theo Tên Phòng", "Sắp Xếp theo Số lượng thiết bị mỗi phòng" }));
        sapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapXepActionPerformed(evt);
            }
        });

        tttk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tttk.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton10)
                                .addGap(45, 45, 45)))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(sapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tttk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addGap(51, 51, 51)
                                .addComponent(jButton9))
                            .addComponent(tk, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 8, Short.MAX_VALUE)))
                        .addGap(101, 101, 101))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(sapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tttk, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sắp Xếp & Tìm Kiếm", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenPhongActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableDSPhong.getModel();
        tenPhong.setEnabled(true);
        tenPhong.setText((String) model.getValueAt(
                tableDSPhong.getSelectedRow(), tableDSPhong.getSelectedColumn()));
        // TODO add your handling code here:
    }//GEN-LAST:event_tenPhongActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        tenPhong.setEnabled(true);
        if(!tenPhong.getText().equals("")){
            PhongHoc p = new PhongHoc();
            if(phong.size() != 0){
                p.setID(1+((PhongHoc)phong.get(phong.size()-1)).getID());
            }
            p.setName(tenPhong.getText());
            p.setSoGhe(Integer.parseInt(soG.getItemAt(soG.getSelectedIndex())));
            DefaultTableModel model = (DefaultTableModel) tableDSPhong.getModel();
            model.addRow(new Object[]{
                p.getID(), p.getName(), p.getSoGhe()
            });
            phong.add(p);
            ioFile.ghiFile(phong, "DSPHONG.DAT");
        }
        else{
            JOptionPane.showMessageDialog(this, "Hãy nhập đầy đủ thông tin!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileActionPerformed
        DefaultTableModel model = (DefaultTableModel)tableDSPhong.getModel();
        for(Object o: phong){
            model.addRow(new Object[]{
                ((PhongHoc)o).getID(), ((PhongHoc)o).getName(), ((PhongHoc)o).getSoGhe()
            });
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loadFileActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableDSPhong.getModel();
        model.setRowCount(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        tenPhong.setText("");
    }//GEN-LAST:event_cancelActionPerformed

    private void tenTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenTBActionPerformed
    }//GEN-LAST:event_tenTBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!tenTB.getText().equals("")){
            ThietBi t = new ThietBi();
            if(thietBi.size() != 0)
                t.setID(((ThietBi)(thietBi.get(thietBi.size()-1))).getID()+1);
            t.setName(tenTB.getText());
            t.setXuatxu(xx.getItemAt(xx.getSelectedIndex()));
            t.setNam(Integer.parseInt(namSX.getItemAt(namSX.getSelectedIndex())));
            DefaultTableModel model = (DefaultTableModel) tableThietBi.getModel();
            model.addRow(new Object[]{t.getID(), t.getName(), t.getXuatxu(), t.getNam()});
            thietBi.add(t);
            ioFile.ghiFile(thietBi, "DSTB.DAT");
        }
        else JOptionPane.showMessageDialog(this, "Hãy nhập đầy đủ thông tin!");
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableThietBi.getModel();
        for(Object o: thietBi){
            ThietBi t = ((ThietBi)o);
            model.addRow(new Object[]{t.getID(), t.getName(), t.getXuatxu(), t.getNam()});
        }
        if(thietBi.size() == 0) JOptionPane.showMessageDialog(this, "DS rong.");
            
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableThietBi.getModel();
        model.setRowCount(0);
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tenTB.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbIDActionPerformed

    private void load3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load3ButtonActionPerformed
        if(list.size()!= 0){
             DefaultTableModel model = (DefaultTableModel) table3.getModel();
             for(GiaoTiep g: list){
                 QLTB q = ((QLTB)g);
                 model.addRow(new Object[]{
                     q.getPhongHoc().getID(), q.getPhongHoc().getName(), 
                     q.getThietBi().getID(), q.getThietBi().getName(),
                     q.getSoLuong(), q.getTrangThai()
                 });
             }

        }
        else{
            JOptionPane.showMessageDialog(this, "Danh Sách Rỗng.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_load3ButtonActionPerformed

    private void clear3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear3ButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) table3.getModel();
        model.setRowCount(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_clear3ButtonActionPerformed

    private void cancel3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel3ButtonActionPerformed
        pID.setText("");
        tbID.setText("");
        sl.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel3ButtonActionPerformed

    private void add3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add3ButtonActionPerformed
        if(!pID.getText().equals("") && !tbID.getText().equals("")&& !sl.getText().equals("")){
            int pid = Integer.parseInt(pID.getText());
        int tID = Integer.parseInt(tbID.getText());
        QLTB q = new QLTB();
        boolean bb = false, bb1 = false;
        for(GiaoTiep P: phong){
            if(((PhongHoc)P).getID() == pid){
                q.setPhongHoc(((PhongHoc)P));
                bb = true;
            }
        }
        if(!bb){
            JOptionPane.showMessageDialog(this, "Nhập sai mã phòng.");
        }
        
        for(GiaoTiep g: thietBi){
            if(((ThietBi)g).getID() == tID){
                q.setThietBi(((ThietBi)g));
                bb1 = true;
            }
        }
        if(!bb1) JOptionPane.showMessageDialog(this, "Nhập sai mã thiết bị.");
        for(GiaoTiep qq: list){
            if(((QLTB)qq).getThietBi().getID() == tID 
                    && ((QLTB)qq).getPhongHoc().getID() == q.getPhongHoc().getID()){
                JOptionPane.showMessageDialog(this, "Mã TB đã tồn tại.");
                bb1 = false;
            }
        }   
        if(bb && bb1){
            q.setSoLuong(Integer.parseInt(sl.getText()));
            q.setTrangThai(tt.getItemAt(tt.getSelectedIndex()));
            DefaultTableModel model = (DefaultTableModel) table3.getModel();
            model.addRow(new Object[]{
                q.getPhongHoc().getID(), q.getPhongHoc().getName(), q.getThietBi().getID(),
                q.getThietBi().getName(), q.getSoLuong(), q.getTrangThai()
                    
            });
            list.add(q);
            ioFile.ghiFile(list, "QLTB.DAT");
        }
        }
        else JOptionPane.showMessageDialog(this, "Hãy nhập đầy đủ thông tin.");
                
    }//GEN-LAST:event_add3ButtonActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(list.size()!= 0){
             DefaultTableModel model = (DefaultTableModel) table4.getModel();
             model.setRowCount(0);
             for(GiaoTiep g: list){
                 QLTB q = ((QLTB)g);
                 model.addRow(new Object[]{
                     q.getPhongHoc().getID(), q.getPhongHoc().getName(), 
                     q.getThietBi().getID(), q.getThietBi().getName(),
                     q.getSoLuong(), q.getTrangThai()
                 });
             }

        }
        else{
            JOptionPane.showMessageDialog(this, "Danh Sách Rỗng.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(list.size()!= 0){
            if(!tk.getText().equals("")){
            int count = 0;
             DefaultTableModel model = (DefaultTableModel) table4.getModel();
             model.setRowCount(0);
             for(GiaoTiep g: list){
                 QLTB q = ((QLTB)g);
                 
                     if(q.getPhongHoc().getName().matches(".*"+tk.getText()+".*")){
                            count++;
                            model.addRow(new Object[]{
                            q.getPhongHoc().getID(), q.getPhongHoc().getName(), 
                            q.getThietBi().getID(), q.getThietBi().getName(),
                            q.getSoLuong(), q.getTrangThai()
                        });
                    }

                 
             }
             if(count==0) JOptionPane.showMessageDialog(this, "Không tìm thấy. Hãy thử từ khóa khác.");
             else tttk.setText("Tìm thấy kết quả cho \""+tk.getText()+"\"");
        
            } else{
                     JOptionPane.showMessageDialog(this, "Nội dung tìm kiếm không hợp lệ.");
                 }
        }
        else{
            JOptionPane.showMessageDialog(this, "Danh Sách Rỗng.");
                                 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table4.getModel();
             model.setRowCount(0);
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        tk.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void sapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapXepActionPerformed
        SXTimKiem sx = new SXTimKiem();
        if(sapXep.getSelectedIndex() == 0){
            sx.sortByName(list);
            if(list.size()!= 0){
                DefaultTableModel model = (DefaultTableModel) table4.getModel();
                model.setRowCount(0);
             for(GiaoTiep g: list){
                 QLTB q = ((QLTB)g);
                 model.addRow(new Object[]{
                     q.getPhongHoc().getID(), q.getPhongHoc().getName(), 
                     q.getThietBi().getID(), q.getThietBi().getName(),
                     q.getSoLuong(), q.getTrangThai()
                 });
             }
            }
        }
        else{
            sx.sortBySL(list);
            if(list.size()!= 0){
                DefaultTableModel model = (DefaultTableModel) table4.getModel();
                model.setRowCount(0);
                for(GiaoTiep g: list){
                    QLTB q = ((QLTB)g);
                    model.addRow(new Object[]{
                        q.getPhongHoc().getID(), q.getPhongHoc().getName(), 
                        q.getThietBi().getID(), q.getThietBi().getName(),
                        q.getSoLuong(), q.getTrangThai()
                    });
                }
            }
        }
        
    }//GEN-LAST:event_sapXepActionPerformed

    private void tableDSPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDSPhongMouseClicked
        DefaultTableModel model = (DefaultTableModel) tableDSPhong.getModel();
        if(tableDSPhong.getSelectedRow() != -1){
            tenPhong.setText((String)model.getValueAt(tableDSPhong.getSelectedRow(),
                1 ));
        }
    }//GEN-LAST:event_tableDSPhongMouseClicked

    private void tableThietBiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableThietBiMouseClicked
        DefaultTableModel model = (DefaultTableModel) tableThietBi.getModel();
        if(tableThietBi.getSelectedRow() != -1){
            tenTB.setText((String)model.getValueAt(tableThietBi.getSelectedRow(),
                1 ));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tableThietBiMouseClicked

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_table3MouseClicked

    private void tkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tkMouseClicked
        tk.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_tkMouseClicked

    private void tkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tkMouseExited
     //   tk.setText("Ví dụ: 502-A2");
        // TODO add your handling code here:
    }//GEN-LAST:event_tkMouseExited

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        DefaultTableModel model = (DefaultTableModel) table3.getModel();
        if(table3.getSelectedRow() != -1){
            pID.setText(model.getValueAt(table3.getSelectedRow(), 0 ).toString());
            tbID.setText(model.getValueAt(table3.getSelectedRow(), 2 ).toString());
            sl.setText(model.getValueAt(table3.getSelectedRow(), 4 ).toString());
        }
        else JOptionPane.showMessageDialog(this, "Invalid value");
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if(!sl.getText().equals("") ){
            DefaultTableModel model = (DefaultTableModel) table3.getModel();
            model.setValueAt(Integer.parseInt(sl.getText()), table3.getSelectedRow(), 4);
            model.setValueAt(tt.getSelectedItem().toString(), table3.getSelectedRow(), 5);
            QLTB q = (QLTB)list.get(table3.getSelectedRow());
            q.setSoLuong(Integer.parseInt(sl.getText()));
            q.setTrangThai(tt.getSelectedItem().toString());
            list.set(table3.getSelectedRow(), q);
            ioFile.ghiFile(list, "QLTB.DAT");
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid action.");
                    
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       DefaultTableModel model = (DefaultTableModel) tableDSPhong.getModel();
        model.setValueAt((tenPhong.getText()), tableDSPhong.getSelectedRow(), 1);
        PhongHoc q = (PhongHoc)phong.get(tableDSPhong.getSelectedRow());
        q.setName((tenPhong.getText()));
        phong.set(tableDSPhong.getSelectedRow(), q);
        ioFile.ghiFile(phong, "DSPHONG.DAT");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableThietBi.getModel();
        model.setValueAt((tenTB.getText()), tableThietBi.getSelectedRow(), 1);
        model.setValueAt(xx.getSelectedItem().toString(), tableThietBi.getSelectedRow(), 2);
        model.setValueAt(namSX.getSelectedItem().toString(), tableThietBi.getSelectedRow(), 3);
        ThietBi q = (ThietBi)thietBi.get(tableThietBi.getSelectedRow());
        q.setName((tenTB.getText()));
        q.setXuatxu(xx.getSelectedItem().toString());
        q.setNam(Integer.parseInt(namSX.getSelectedItem().toString()));
        thietBi.set(tableThietBi.getSelectedRow(), q);
        ioFile.ghiFile(thietBi, "DSTB.DAT");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BangHienThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BangHienThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BangHienThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BangHienThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BangHienThi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add3Button;
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel3Button;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clear3Button;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton load3Button;
    private javax.swing.JButton loadFile;
    private javax.swing.JComboBox<String> namSX;
    private javax.swing.JTextField pID;
    private javax.swing.JComboBox<String> sapXep;
    private javax.swing.JButton save;
    private javax.swing.JTextField sl;
    private javax.swing.JComboBox<String> soG;
    private javax.swing.JTable table3;
    private javax.swing.JTable table4;
    private javax.swing.JTable tableDSPhong;
    private javax.swing.JTable tableThietBi;
    private javax.swing.JTextField tbID;
    private javax.swing.JTextField tenPhong;
    private javax.swing.JTextField tenTB;
    private javax.swing.JTextField tk;
    private javax.swing.JComboBox<String> tt;
    private javax.swing.JLabel tttk;
    private javax.swing.JComboBox<String> xx;
    // End of variables declaration//GEN-END:variables
}
